@startuml
autonumber
user --[#red]> weibo_relations: 对用户添加新的关注

user --[#red]> weibo_relations:被关注的用户添加粉丝
note right
    RowKey:用户ID
    ColumnFamily:attends,fans
    ColumnLabel:关注用户ID，粉丝用户ID
    ColumnValue:用户ID
    Version：1个版本
end note

user --[#red]> weibo_content:取出来的关注的人所发布的微博的rowkey

user --[#red]> receive_content_email:将取出的关注人的微博rowkey存放到表中
note right
    当前操作用户的微博收件箱添加
    所关注的用户发布的微博rowkey

    RowKey:用户ID
    ColumnFamily:info
    ColumnLabel:用户ID-发布微博的人的用户ID
    ColumnValue:关注的人的微博的RowKey
    Version:1000
end note
@enduml